# -*- coding: utf-8 -*-
"""Another copy of simple_linear_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AUyf2YQseDke_OXxxzMI198gtFgkDwNT
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv("linear reg.csv")
X = dataset.iloc[:, 1:2].values
y = dataset.iloc[:, -1].values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 1)

from sklearn.linear_model import LinearRegression

regressor = LinearRegression()
regressor.fit(X_train,y_train)

y_pred = regressor.predict(X_test)

plt.scatter(X_train, y_train, color='red')
plt.plot(X_train, regressor.predict(X_train), color="blue")
plt.title("Test Score vs Hours Studied (Training Dataset)")
plt.xlabel("Hours Studied")
plt.ylabel("Test score")
plt.show()

plt.scatter(X_test, y_test, color='red')
plt.plot(X_train, regressor.predict(X_train), color="blue")
plt.title("Test Score vs Hours Studied (Test Dataset)")
plt.xlabel("Hours Studied")
plt.ylabel("Test score")
plt.show()