training:
  batch_size: 128
  num_workers: 2
  epochs: 10
  lr: 0.001
  weight_decay: 0.0
  beta: 1.0
  device: auto
  seed: 2024
  model_output: checkpoints/vae.pth
model:
  latent_dim: 16
logging:
  save_metrics: results/vae_metrics.json
  sample_dir: results/vae_samples
